# Generated by Django 4.1.7 on 2023-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_to_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrowing_return',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cd_auth',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='duration',
            field=models.DateField(blank=True),
        ),
    ]
