# Generated by Django 4.1.7 on 2023-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_borrowed_to_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
